version: '3'

volumes:
  database:
  uploads:

services:

  # Frontend with ISR
  web-app:
    build: ./web
    restart: always
    
    expose:
      - "3000"

    volumes:
      - ./web:/app

  # Proxy for different micro services
  nginx:
    build: ./nginx
    restart: always

    ports:
      - "80:80"
      - "443:443"
    
    depends_on:
      - web-app
      - ingestion

  mysql:
    image: mysql:8
    restart: always

    volumes:
      - database:/var/lib/mysql
      # init scripts go below here
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/1.sql"
    
    environment:
      - MYSQL_DATABASE=my_tube
      - MYSQL_ROOT_PASSWORD=startpw+1

    expose:
      - "3306"

    ports:
      - "3306:3306"

  # save uploaded videos
  ingestion:
    build: ./ingestion
    restart: always

    expose:
      - "5000"

    volumes: 
      - uploads:/app/uploads