name: Docker Image CI

on:
  push:
    branches: [ "stable" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get the time :)
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
    
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Log into container registry
      uses: docker/login-action@v2.1.0
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Extract metadata (tags, labels) Nginx image
      id: meta-nginx
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/mytube_nginx
    
    - name: Build nginx
      uses: docker/build-push-action@v3.2.0
      with:
        context: nginx
        file: nginx/Dockerfile
        push: true
        tags: ${{ steps.meta-nginx.outputs.tags }}
        labels: ${{ steps.meta-nginx.outputs.labels }}
        
    - name: Extract metadata (tags, labels) Nginx image
      id: meta-web
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/mytube_web 
        
    - name: Build web
      uses: docker/build-push-action@v3.2.0
      with:
        context: web
        file: web/Dockerfile
        push: true
        tags: ${{ steps.meta-web.outputs.tags }}
        labels: ${{ steps.meta-web.outputs.labels }}
        
