name: Docker Image CI

on:
  push:
    branches: [ "stable" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Log into container registry
      uses: docker/login-action@v2.1.0
      with: 
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
    
    - name: Build nginx
      uses: docker/build-push-action@3.2.0
      with:
        context: nginx
        file: nginx/Dockerfile
        push: true
        tags: mytube_nginx:$(date +%s)
        
    - name: Build web
      uses: docker/build-push-action@3.2.0
      with:
        context: web
        file: web/Dockerfile
        push: true
        tags: mytube_web:$(date +%s)
